sudo: required
language: cpp
services:
  - docker
  
before_install:
  - docker pull glebka/jenkins-vr-buildenv

script:
  - docker run --rm -t -i glebka/jenkins-vr-buildenv /bin/sh -c "git clone https://github.com/Glebka/jenkins-vr.git; cd /jenkins-vr; cmake . && make"
