sudo: required
language: cpp
services:
  - docker
  
before_install:
  - docker build -t buildenv .
  - docker run --rm -t -i buildenv

before_script:
  - cd /root/jenkins-vr

script:
  - cmake .
  - make
