sudo: required
language: cpp
services:
  - docker
  
before_install:
  - docker build -t buildenv .
  - docker run buildenv /bin/sh -c "cd /root/jenkins-vr; cmake . && make"

script:
  - cmake .
  - make
